### ISSUE TITLE
Bug with shield

### ISSUE THREAD

**Issue by T3nac1ty** [shirograhm/TooManyItemsRoR2#23] opened 2024-09-07 23:16 UTC
Something in the mod is making the shield on overloading enemies recharge at a speed where they're unkillable. It happens on survivors with shield items too, but to a lesser degree.

**Comment by shirograhm** [comment] 2024-09-07 23:56
Duplicate of issue #21. Bugfix should be out in v0.5.1.

**Closed by shirograhm** 2024-09-07 23:56 UTC
