### ISSUE TITLE
Fleece Hoodie applies to shield recharge timer

### ISSUE THREAD

**Issue by cesmaster644** [shirograhm/TooManyItemsRoR2#2] opened 2024-05-01 08:26 UTC
I can only assume that it could apply to other similar "buffs"/"debuffs" that are used as timers like that, but I noticed that it will actually _increase_ your shield recharge delay if that's the next "buff" you get while it's off cooldown.

**Comment by shirograhm** [comment] 2024-05-06 22:37
I need more detail for this. Can you give me more detail on the situation in which this bug happened (what shield you mean, items in inventory, survivor played)? I tested the Void DLC Safer Spaces shield as well as the generic Shield Generator while out-of-combat and could not reproduce any issue.

**Comment by shirograhm** [comment] 2024-05-18 03:32
I am closing this as I cannot reproduce it.

**Closed by shirograhm** 2024-05-18 03:32 UTC
